name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        run: yarn install

      - name: Build
        env:
          APP_URL: https://citation-creator.com
        run: yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: public
